export const CART_ADD_ITEM = 'CART_ADD_ITEM';
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM';
export const CART_FETCH_SUCCESS = 'CART_FETCH_SUCCESS';
export const SET_LOADING_STATE = 'SET_LOADING_STATE';
